// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThesesWebApi.Data;

#nullable disable

namespace ThesesWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230514160611_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ThesesWebApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThesisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThesisId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ThesesWebApi.Models.Thesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MainAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainAuthorId");

                    b.ToTable("Theses");
                });

            modelBuilder.Entity("ThesesWebApi.Models.Person", b =>
                {
                    b.HasOne("ThesesWebApi.Models.Thesis", null)
                        .WithMany("OtherAuthors")
                        .HasForeignKey("ThesisId");
                });

            modelBuilder.Entity("ThesesWebApi.Models.Thesis", b =>
                {
                    b.HasOne("ThesesWebApi.Models.Person", "MainAuthor")
                        .WithMany()
                        .HasForeignKey("MainAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainAuthor");
                });

            modelBuilder.Entity("ThesesWebApi.Models.Thesis", b =>
                {
                    b.Navigation("OtherAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
